embeddings {
  tensor_name: "embedding:0"
  metadata_path: "G:/DeepLearning/noopy/tensorflow_demo_1/projector/projector/metadata.tsv"
  sprite {
    image_path: "G:/DeepLearning/noopy/tensorflow_demo_1/projector/data/mnist_10k_sprite.png"
    single_image_dim: 28
    single_image_dim: 28
  }
}
